apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - supplychain/namespace.yaml
  - supplychain/ca/ca.yaml
  - org1/namespace.yaml
  - org1/ca/ca.yaml
  - org2/namespace.yaml
  - org2/ca/ca.yaml
